server:
  port: 8080
spring:
  application:
    name: authen-service
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    mongodb:
      uri: ${MONGODB_URI}
    web:
      pageable:
        size-parameter: size
        page-parameter: page
        default-page-size: 20
        max-page-size: 100
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
        temp.use_jdbc_metadata_defaults: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${USERNAME_EMAIL}
    password: ${PASSWORD_EMAIL}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
elasticsearch:
  host: ${ELASTICSEARCH_HOST}
  port: ${ELASTICSEARCH_PORT}
  clustername: ${CLUSTER_NAME}
twilio:
  account_sid: ${TWILIO_ACCOUNT_SID}
  auth_token: ${TWILIO_AUTH_TOKEN}
  twilio_number: ${TWILIO_NUMBER}
app:
  jwtSecret:
    token: ${JWT_SECRET_TOKEN}
  jwtExpirationInMs:
    token: ${JWT_TIME}
time:
  refresh-token: ${TIME_REFRESH_TOKEN}
  register: ${EXPIRE_TIME_REGISTER}
  forgot-password: ${EXPIRE_TIME_FORGOT_PASSWORD}
